Encoding.default_external = Encoding::UTF_8

default_platform :ios

platform :ios do
  lane :bump do |options|
    if !options[:tag_name]
      UI.user_error!("No 'tag_name' provided")
    end

    tag_name = options[:tag_name]

    # zip all xcframework
    xcframeworks = []
    xcframework_paths = []
    Dir.chdir('..') do
      Find.find('Carthage/Build/') do |path|
        xcframework_paths << path if path =~ /.*\.xcframework$/
      end
    end
    xcframework_paths.each do |xcframework_path|
      xcframework_name = xcframework_path.split('/').last
      zip_path = "zipped/#{xcframework_name}.zip"
      zip(path: xcframework_path, output_path: zip_path)
      checksum = Digest::SHA256.hexdigest File.read "../#{zip_path}"
      xcframeworks << {
        name: File.basename(xcframework_name, File.extname(xcframework_name)),
        checksum: "#{checksum}",
        url:
          "https://github.com/nrohwedder/ios-dependencies/tree/#{tag_name}/zipped/#{xcframework_name}.zip",
      }
    end

    # Generate Package.swift
    erb(
      template: 'fastlane/templates/Package.swift.erb',
      destination: 'Package.swift',
      placeholders: {
        xcframeworks: xcframeworks,
      }
    )
  end
end